schema_version: 1

context:
  python_min: "3.10"
  version: "1.1.1"

package:
  name: trame-colormaps
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/trame-colormaps/trame_colormaps-${{ version }}.tar.gz
  sha256: af611e657510218fd436decbc0fbec4c283c99dd23f06a39a8666ca50af7bfa9

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - trame >=3
    - trame-dataclass >=2
    - trame-vuetify >=3.2
    - vtk

tests:
  - python:
      imports:
        - trame_colormaps
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Self-contained colormap module for VTK color transfer functions in Trame apps
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/Kitware/trame-colormaps

extra:
  recipe-maintainers:
    - jourdain
